services:

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - 8090:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: Admin@123
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:8.0
    container_name: mysql-wordpress
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin@123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
