version: '3.9'
services:
  apache:
    image: httpd:latest
    container_name: my-apache-app-compose
    ports:
    - '8080:80'
    volumes:
      - /home/monir/mygithub/docker-project/apache:/usr/local/apache2/htdocs
